### PR TITLE
Pytest decorators, restructuring

### PR DESCRIPTION
**Pull request by oskardrenske-ith**
@pytest.mark.x to be able to run a subset of tests, and to reuse tests between historical and job search
some restructuring and renaming of directories

### CODE REVIEW

**Comment by erik-gbg** [comment]
More organizing the code - I love it!

1. We should really have a script running through all of the api tests.

2. Do we really need the complete group? 3 apps -> 3 groups I thought.

3. Often there is:
@pytest.mark.jobsearch
@pytest.mark.historical

The disadvantage is that the same thing is tested twice and the whole process takes longer time.
The advantage is obviously that some tiny detail (in the rare cases) will make jobsearch and historical different.
So this is a trade off...

4. Maybe you should give a short presentation to the group, Oskar.

**Comment by erik-gbg** [comment]
I haven't succeeded in running this yet.

**Comment by erik-gbg** [comment]
I would love to being able to run it the old way.
Let's say the following directories: searching, jobsearch, historical, jobstream

**Review by erik-gbg — APPROVED** [review]

**Comment by erik-gbg** [comment]
And well, a script to run them all would be nice - new Jira?

**Review by halge — APPROVED** [review]

**Pull request merged**
