### PR TITLE
Nar 1579 historical stats endpoint

### PR DESCRIPTION
**Pull request by lina1101**

### CODE REVIEW

**Comment by oskardrenske-ith** [comment]
Put restructuring in a separate branch, and let this be only about historical stats

**Review by erik-gbg — CHANGES_REQUESTED** [review]
No restructuring in a branch like this one.
image
To put it simply: No creation of directories.
Do restructuring in separate branches for restructuring jiras.

**Comment by erik-gbg** [comment]
Much better!
However, if there's going to be a /stats directory(which I find acceptable), then I think it belongs one level up (not inside repository). I.e. sokannonser/stats/ instead of sokannonser/repository/stats/
What does @oskardrenske-ith and @halge think?

**Review by oskardrenske-ith — APPROVED** [review]

**Review by erik-gbg — APPROVED** [review]

**Comment by erik-gbg** [comment]
See the /stats directory as a temporary structure for now. Then think it through, together with the discussion in the Mattermost channel Restructuring/renaming, in order to get a good organization of the code.
Also consider using the QueryBuilder in the future, e.g. in order to use the _typeahead_aggs() function. Which is the one the can create statistics in "human readable" style à la PB.

**Review by halge — APPROVED** [review]

**Review by halge — APPROVED** [review]

**Pull request merged**
